// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Crud_Generator
{
    internal sealed partial class Vsix
    {
        public const string Id = "Crud_Generator.e1d7391e-83ea-49cd-a8c1-5a3d6940c95e";
        public const string Name = "Crud_Generator";
        public const string Description = @"Crud generator.Uma ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Matheus Romeike";
        public const string Tags = "";
    }
}
